// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtrqvjhegeysqfmjeuwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10cnF2amhlZ2V5c3FmbWpldXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNzg4NTIsImV4cCI6MjA1Mzg1NDg1Mn0.w6Xdv2wljCjnQp1O5wEvEvdhCwq_w51I2r623GE90Fo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);